### ISSUE TITLE
Support for return statement

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#15]
prettier-ruby is currently missing support for return statements:

```ruby
def do_things(x)
  return if x.nil?

  x.side_effect!
end
```

Example:

> {"ast_type":"return0","error":"Unhandled node: return0"}

**Comment by iamsolankiamit** [comment]
We support `return` statement, need to add support for blank returns [`return0`].

**Comment by AlanFoster** [comment]
Hoping a contributor picks this up as an easy ticket to deliver 🤞

**Comment by AlanFoster** [comment]
@iamsolankiamit Could you grant the privileges for me to add labels to issues? I would like to place `good first issue` labels to a few of the tickets I have raised :+1:

**Comment by AlanFoster** [comment]
@iamsolankiamit Thanks! :+1:

**Comment by iamsolankiamit** [comment]
Fixed in b460ae1
