### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by gurgeous** [iamsolankiamit/prettier-ruby#2]
Suggestion... could you add some pointers to the readme on contributing? If you want help, you could add stuff like:

- how to install
- how to try it with a ruby file
- how to run tests
- how to submit PRs
- some hints on how it works

There's plenty of room for prettier-ruby in the Ruby ecosystem, along with `rubocop -a` and `rufo`. I'm sure people would be happy to contribute if you made it easy. Thanks for getting this started!

**Comment by davidalejandroaguilar** [comment]
Totally agree, `prettier` for JS is awesome, it'd be great to have it fully working for Ruby.

**Comment by iamsolankiamit** [comment]
I had been super busy past few weeks. I am aware that the documentation and contributing guidelines aren't done yet, will push them in few days, along with a working alpha 🔥

**Comment by iamsolankiamit** [comment]
Major Update, Have removed external gem dependencies for parsing and unparsing ruby code. Now we do it using Ripper(included with ruby).

Contributing and style guide will be added soon. Aiming to release the alpha version soon.

Thanks for following the project.

**Comment by AlanFoster** [comment]
To try and help out; I've created some tickets that show an example Ruby code snippet that currently isn't supported by prettier ruby that would be a good starting point for contributing code fixes :)
