### ISSUE TITLE
Add support for `begin` syntax

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#36]
Add support for the following syntax:

```ruby
def foo
  begin
   something_dangerous!
  rescue => e
    puts "Oops."
  end
end
```

Current error:

```
 {"ast_type":"begin","error":"Unhandled node within astexport.rb: begin"}
```

**Comment by iiska** [comment]
This is something I would be interested on implementing if anyone else isn't working on it yet?

Based on existing codebase my plan would be following:

1. Failing test case for `begin`
2. Extend `vendor/ruby/astexport.rb` for syntax
3. Implement syntax to `src/printer/index.js`
4. Extend tests to test other `begin` uses, eg. assignation.

**Comment by iamsolankiamit** [comment]
Great, submit a pr when you can

**Comment by tommoor** [comment]
Seems like this should be closed?
