### ISSUE TITLE
Support string concat syntax

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#43]
Prettier-ruby does not currently support the following syntax:

```ruby
raise "Long message with detailed reason why something happened which caused" \
      "the developer to write a well placed string concat"
```

## Current Output 

```
raise({"ast_type":"string_concat","error":"Unhandled node within astexport.rb: string_concat"})
```

## Expected Output

For MVP of prettier-ruby I assume outputting roughly the same input is fine for now, there shouldn't be any attempt to split/join the separate string sections together, or align with the prettier column width configuration value. Although it would be good to support this in the future perhaps.

**Comment by hakusaro** [comment]
Shouldn’t this be closed since #58 has been merged?
