### ISSUE TITLE
Support dyna symbols

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#49]
Prettier-ruby doesn't currently handle dyna symbols and its variations.

Sample code:

```ruby
{
  :"hello-world" => "helloWorld",
  "foo-bar-baz": 20,
  "#dynamic-key-#{foo}": 10
}
```

I believe implementing this fully right now is blocked on the ability to correlate sexpressions with underlying tokens

**Comment by iamsolankiamit** [comment]
Fixed in 67fe77d
