### ISSUE TITLE
Correlate underlying tokens with sexpressions

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#50]
Just creating an issue to keep track of correlating the underlying tokens with sexpressions which is currently blocking support for embedded expressions, heredoc support, single/double quote formatting, String/Symbol array support etc.

I don't currently have a good solution for this, but I'm tempted to say that since both the sexpressions and tokens both contain the row/column locations, perhaps it would be possible to have a pre-built useful hashmap of sexpression location to underlying token for fast lookup - but I'm not sure of all of the possible edge cases here just yet though.

**Comment by AlanFoster** [comment]
I've added a `requires tokens` label to track issues that depend on this functionality 🎉

**Comment by AlanFoster** [comment]
@iamsolankiamit I've been playing around with this, and I wonder if it's possible to make use of Ripper's `on_#{event}` callbacks to attach the meta-data directly to the next parsed sexpression that it generates? 🤔

We can create our own custom Ripper parser by following pretty closely to the out of the box implementation [here](https://github.com/ruby/ruby/blob/fff17079d7501bb57eefb7a6a65aac8aaecf98da/ext/ripper/lib/ripper/sexp.rb). We'd listen to the scanner events and then attach the comments, and start/end token information for single/double quotes, heredoc information, qwords and qsymbol tokens to the next parse event sexpression.

If we implement out own ripper implementation we could move remove the need for an additional separate pass of lexing too, which would help with performance of larger files

**Comment by iamsolankiamit** [comment]
that was the previous implementation, but with ruby-parser gem. it quickly gets complicated to manage.

**Comment by AlanFoster** [comment]
@iamsolankiamit I was playing around with a custom Ripper listener with some simple input:

```ruby
code = <<~'STR'
  # test comment
  "double quotes\n"
  'single quotes \n'

  %i( symbol example )
STR
```

The default ripper implementation doesn't give us all the data we want:

```ruby
[:program,
 [[:string_literal,
   [:string_content, [:@tstring_content, "double quotes\\n", [2, 1]]]],
  [:string_literal,
   [:string_content, [:@tstring_content, "single quotes \\n", [3, 1]]]],
  [:array,
   [[:@tstring_content, "symbol", [5, 4]],
    [:@tstring_content, "example", [5, 11]]]]]]
```

But with a quick spike into a custom Ripper parser, I can get the extra meta-data and bind it to the next parsed node:

```ruby
[:program,
 [[:string_literal,
   [:string_content,
    {:meta=>{:start_quote=>"\"", :comments=>["# test comment\n"]}},
    [:@tstring_content, "double quotes\\n", [2, 1]]],
   {:meta=>{:end_quote=>"\""}}],
  [:string_literal,
   [:string_content,
    {:meta=>{:start_quote=>"'"}},
    [:@tstring_content, "single quotes \\n", [3, 1]]],
   {:meta=>{:end_quote=>"'"}}],
  [:array,
   [[:@tstring_content, "symbol", [5, 4]],
    [:@tstring_content, "example", [5, 11]]],
   {:meta=>{:start_quote=>"%i( ", :newline=>true}}]]]
```

There's now the extra data directly in the tree showing the start/end quotes, comments, and whether there was a newline associated with that node

**Comment by AlanFoster** [comment]
I just noticed a new prettier for ruby appear too, which makes use of a similar approach for tracking comments - but the Ripper implementation has been bundled as a JS dependency:

- https://github.com/kddeisz/prettier-ruby
- https://github.com/kddeisz/ripperjs

**Comment by iamsolankiamit** [comment]
So tokens have been implemented, need to add it where-ever required.
