### ISSUE TITLE
Add support for array destructuring / constructing using splat syntax

### ISSUE THREAD

**Issue by iiska** [iamsolankiamit/prettier-ruby#60]
Array unwrapping / wrapping with splat:

``` ruby
def foo(a = {})
  some_args = a[:foo] || []
  [*some_args].map do |i|
    some_stuff_with i
  end
end
```

Current error:
```
vendor/ruby/astexport.rb:170:in `visit': undefined method `first' for :args_add_star:Symbol (NoMethodError)
```

Array destructuring:

``` ruby
first, *, last = [1,2,3,4,5]
```

Current error:

```
vendor/ruby/astexport.rb:170:in `visit': undefined method `first' for nil:NilClass (NoMethodError)
```

Array constructing or flattening:

``` ruby
a = [1,2]
b = [3,4]
flattened = [*a, *b]
```

Current error:

```
vendor/ruby/astexport.rb:170:in `visit': undefined method `first' for :args_add_star:Symbol (NoMethodError)
```

**Comment by iiska** [comment]
That destructuring error was caused by missing `nil?` check when naming the middle part was discarded using only splat without variable name.

Got that fixed at https://github.com/iiska/prettier-ruby/commit/0b706ffe181b5cc878c455db382b22ce5729c6ea, but I'll make PR after I've implemented other splat use cases too.

**Comment by iiska** [comment]
I started adding those test cases under `tests/array` at `splats.rb`, do you feel that its correct place considering the feature and ways you organize codebase?

**Comment by iamsolankiamit** [comment]
yes, it is.
