### ISSUE TITLE
Missing `unless` support

### ISSUE THREAD

**Issue by AlanFoster** [iamsolankiamit/prettier-ruby#9]
prettier-ruby currently fails on:

```ruby
unless false
  puts "this is true"
end
```

With:

> {"ast_type":"unless","error":"Unhandled node: unless"}

**Comment by AlanFoster** [comment]
There appears to be `unless_mod` too:

```ruby
(0..100).each do |i|
  next unless i % 2 == 0

  puts i
end
```

> {"ast_type":"unless_mod","error":"Unhandled node: unless_mod"}

**Comment by iamsolankiamit** [comment]
This should be easy to do, check out if, until, etc. This follows the same pattern.

**Comment by iamsolankiamit** [comment]
Fixed!
